---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      chart: podinfo
      version: 10.x
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: podinfo
  valuesFrom:
    - kind: ConfigMap
      name: podinfo-helm-chart-value-overrides
      valuesKey: values.yaml
